### ISSUE TITLE
[Question] Usage without router

### ISSUE THREAD

**Issue by vestimir** [Daydreamer-riri/vite-react-ssg#10]
Can I use the package without a router, like https://github.com/antfu/vite-ssg#single-page-ssg? 

I'm trying to build a minimal setup that creates an HTML file with prerendered React, single JS bundle file and single CSS file. 

Is this possible?

**Comment by Daydreamer-riri** [comment]
Sure.  I will release this feature as soon as possible.  Thanks for your advice.

**Comment by Daydreamer-riri** [comment]
Hi @vestimir , you can use Vite-React-SSG@0.6.0 to implement Single Page SSG.

See: [vite-react-ssg get started](https://vite-react-ssg.netlify.app/docs/getting-started#single-page-ssg)

**Comment by vestimir** [comment]
Thank you!
