### ISSUE TITLE
React .mjs error when building a project

### ISSUE THREAD

**Issue by ZRunner** [Daydreamer-riri/vite-react-ssg#16]
When building my react project using `vite-react-ssg build`, I get an error about some react index.mjs file not found. Here's the end of traceback:

```
[vite-react-ssg] Build for server...
vite v5.2.6 building SSR bundle for production...
✓ 44 modules transformed.
.vite-react-ssg-temp/ezckg9tybb/assets/GuildDashboard-D2pThusV.js   5.82 kB
.vite-react-ssg-temp/ezckg9tybb/assets/Dashboard-CHa46ohM.js        6.24 kB
.vite-react-ssg-temp/ezckg9tybb/assets/Leaderboard-Tyk-O-aA.js     17.24 kB
.vite-react-ssg-temp/ezckg9tybb/index.mjs                          19.63 kB
✓ built in 78ms

[vite-react-ssg] An internal error occurred.
[vite-react-ssg] Please report an issue, if none already exists: https://github.com/daydreamer-riri/vite-react-ssg/issues
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '.../node_modules/@reduxjs/toolkit/query/react' is not supported resolving ES modules imported from .../.vite-react-ssg-temp/ezckg9tybb/index.mjs
Did you mean to import "@reduxjs/toolkit/dist/query/react/index.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:258:11)
    at moduleResolve (node:internal/modules/esm/resolve:924:10)
    at defaultResolve (node:internal/modules/esm/resolve:1148:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///.../node_modules/@reduxjs/toolkit/query/react'
}

Node.js v21.7.3
```

My repo, if you want to check my configuration or code: https://github.com/ZRunner/Axobot-web/tree/ssg-test

**Comment by Daydreamer-riri** [comment]
This looks similar to this issue：https://github.com/vitejs/vite/issues/15795

I got the same error in node.
![Screenshot_20240421-073225.png](https://github.com/Daydreamer-riri/vite-react-ssg/assets/70067449/aaa8b25b-7fb3-4813-936d-f3533cdb1642)

**Comment by Daydreamer-riri** [comment]
Perhaps you can solve this problem by setting ssr.noExternal (Vite SSR https://vitejs.dev/guide/ssr.html#ssr-externals).

If it is the same problem(https://github.com/vitejs/vite/issues/15795), then this should be a @redux/toolkit problem.

**Comment by ZRunner** [comment]
Setting the `ssr.noExternal`option to `["@reduxjs/toolkit"]` seems to fix this issue. But the `index.mjs` file generated by vite-react-ssg has some issues, which apparently break the build anyway:

```
[vite-react-ssg] Build for server...
vite v5.2.6 building SSR bundle for production...
"freeze" is imported from external module "immer" but never used in "node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js" and "node_modules/@reduxjs/toolkit/dist/query/rtk-query.esm.js".
✓ 47 modules transformed.
.vite-react-ssg-temp/2osfrfhl4k/assets/GuildDashboard-jnCI0FX9.js    5.81 kB
.vite-react-ssg-temp/2osfrfhl4k/assets/Dashboard-BOZIqSk8.js         6.22 kB
.vite-react-ssg-temp/2osfrfhl4k/assets/Leaderboard-CI4q0FFr.js      17.23 kB
.vite-react-ssg-temp/2osfrfhl4k/index.mjs                          172.27 kB
✓ built in 267ms

[vite-react-ssg] An internal error occurred.
[vite-react-ssg] Please report an issue, if none already exists: https://github.com/daydreamer-riri/vite-react-ssg/issues
file://.../web/.vite-react-ssg-temp/2osfrfhl4k/index.mjs:4077
  matcher: isAnyOf(setToken, logout),
                   ^

ReferenceError: Cannot access 'setToken' before initialization
    at file://.../web/.vite-react-ssg-temp/2osfrfhl4k/index.mjs:4077:20
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async build (file://.../web/node_modules/vite-react-ssg/dist/node.mjs:1232:88)
    at async Object.handler (file://.../web/node_modules/vite-react-ssg/dist/node/cli.mjs:47:5)

Node.js v21.7.3
```

For reference, `setToken` is a redux action I've defined in a dedicated redux slice. In the mentioned index.mjs file, it is defined at line 4114 but used at line 4077, hence the error. I can send here the relevant generated code, if you need it.

**Comment by Daydreamer-riri** [comment]
I'll look into this issue tomorrow. Thanks for the report!

**Comment by Daydreamer-riri** [comment]
Hi @ZRunner , you can upgrade your `@reduxjs/toolkit` to the latest version. The version you are currently using has issues with the directory structure, which will prevent it from running directly in node.

This will resolve the issue of `Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '.../node_modules/@reduxjs/toolkit/query/react' is not supported resolving ES modules imported from .../.vite-react-ssg-temp/ezckg9tybb/index.mjs. Did you mean to import "@reduxjs/toolkit/dist/query/react/index.js"?`.

---

About `setToken`, there is a circular reference issue in your code.

https://github.com/ZRunner/Axobot-web/blob/ssg-test/src/repository/redux/tokenStorage/localStorageMiddleware.ts#L4
https://github.com/ZRunner/Axobot-web/blob/ssg-test/src/repository/redux/tokenStorage/tokenSlice.ts#L3

The two files reference each other, causing vite to write the call to `setToken` before its declaration during the packaging process.

Additionally, there are some aspects in the code that have not taken into account server-side rendering, such as the direct use of localStorage and the use of createBrowserRouter, etc. This will all lead to the failure of server-side rendering (since there are no relevant APIs in Node).

**Comment by ZRunner** [comment]
After your explanations, I carefully reconsidered my needs and my goal. I've decided to look for a different solution to the classic SSR, and don't plan to continue with this library.
Since the error that led me to open this ticket was my fault and not the lib's, I'm closing this ticket. Thanks a lot for your time!

**Comment by Daydreamer-riri** [comment]
Sure ❤️. If you still need to build ssg apps with `vite-react-ssg` , I can provide some help.
