### ISSUE TITLE
How to import json file?

### ISSUE THREAD

**Issue by widiu7omo** [Daydreamer-riri/vite-react-ssg#17]
Hello, could you explain to me how to import json file?

Already test with this, but the result still null. 
```typescript
import { useLoaderData } from "react-router-dom";
export async function loader() {
  const blocks = await import("../../generated/article/blocks.json")
  return { blocks }
}
export default function GeneratorPage() {
  const data = useLoaderData()
  console.log(data)
  return (
    <div>
      <a href="/">Back</a>
    </div>
  );
}
```

**Comment by Daydreamer-riri** [comment]
Hi @widiu7omo, in Vite, to dynamically import a JSON file, you need to access its `default` property.

I have updated the example; you can review the code or clone it to try it out: https://github.com/Daydreamer-riri/vite-react-ssg/blob/main/examples/with-loader/src/pages/json.tsx

If there are still any issues, please let me know, and I will respond as soon as possible.

**Comment by widiu7omo** [comment]
Thank you. It's working.
