### ISSUE TITLE
[Support] How to pass a variable to <Outlet />?

### ISSUE THREAD

**Issue by joshkotrous** [Daydreamer-riri/vite-react-ssg#18]
I want to find out how to manage variables that are stored in `index.tsx` or `Layout.tsx`. In my specific case, I have dark mode implemented on my website. This is controlled by variables I am storing in `Layout.tsx`. I also have a blog built out, accessible at `pages/posts/[postname]` that I want to also receive and respect the dark mode setting. Effectively I need to be able to pass props to the `<Outlet/>` component that is called in `Layout.tsx`. Can you help me figure out how to achieve this?

**Comment by Daydreamer-riri** [comment]
The `Outlet` is provided by `react-router` and should not accept parameters; it is only used to render the matching route view. Based on your scenario, you should use a Context to wrap your Layout (or Outlet), and then use useContext to retrieve the state where it is needed.

See: https://react.dev/reference/react/createContext

**Comment by Daydreamer-riri** [comment]
‌‌‌‌If you have any questions regarding usage, feel free to ask me. I will respond as soon as possible.

**Comment by Elias288** [comment]
@Daydreamer-riri I'm having problems with where to place the context provider, as I need it in the Layout, so I need something at a higher level, but at the same time I need the layout to cover the whole app. 

I tried to make the Layout receive `<Outlet />` as `{children}`, but it is not working.

**Comment by Daydreamer-riri** [comment]
Hi @Elias288 , "Layout" is just the name of a component and has no special meaning.

You can do this:
```tsx
  {
    path: '/',
    element: <SomeProvider><Layout /></SomeProvider>,
  }

```

Or:

```tsx
  {
    path: '/',
    Component: () => <SomeProvider><Layout /></SomeProvider>,
  }

```
There are no restrictions here.
