### ISSUE TITLE
server.headers in vite.config.js not work for 'vite-react-ssg dev'  

### ISSUE THREAD

**Issue by er1cw00** [Daydreamer-riri/vite-react-ssg#20]
I have added  COOP and COEP header to vite.config.js, but they do  not work on top-level document for  'vite-react-ssg dev'.

`
export default defineConfig({

    server: {
        headers: {
            'Cross-Origin-Opener-Policy': 'same-origin',
            'Cross-Origin-Embedder-Policy': 'require-corp',
         },
      }
}
`

![image](https://github.com/user-attachments/assets/36055203-b97a-493f-b3dd-83456cb7957c)

**Comment by Daydreamer-riri** [comment]
Hi @er1cw00 , thank you for pointing this out! The latest version (v0.6.3) has fixed this issue, so you can try it!
