### ISSUE TITLE
Prevent generating `title` tag in the head of the document

### ISSUE THREAD

**Issue by johurul-haque** [Daydreamer-riri/vite-react-ssg#23]
Hi! Cool library. 
I'm doing a single-page SSG. Both in development and in production it adds an empty `title` tag at the top of the document head. 

![image](https://github.com/user-attachments/assets/d962d235-cafd-4c58-9280-91882c1ff207)

This empty `title` tag causes the `title` tag at the bottom unused. The bottom tag is what I wrote in my `index.html` file but the top one was generated.

**Comment by Daydreamer-riri** [comment]
Hi @johurul-haque , this is caused by react-helmet-async generating an empty title anyway. I've fixed this in version 0.7.1, you can try it!
