### ISSUE TITLE
Had issue in setup of a S3 + Cloudfront hosting the dist static website

### ISSUE THREAD

**Issue by stouch** [Daydreamer-riri/vite-react-ssg#28]
I setup my S3 with : 
index.html as index and error file.

Then I setup my Cloudfront distribution with a _Origin Request_ Lambda@Edge function (node20) like this : 
```js
import path  from 'path';
export const handler = async (event, context, callback) => {
  const { request } = event.Records[0].cf;
  const { uri, headers } = request;
  if (uri !== "" && uri !== "/" && !uri.includes('.')) {
      request.uri += '.html';
  }
  return request;
};
```

And everything worked then.

Thanks for your repo. Actually, it's insane that building a static site is not more obvious/straightforward when we're using react + vite project. Happily you made this repo 🔥 (I created a thread in react.dev about this last part : https://github.com/reactjs/react.dev/issues/7155)

**Comment by Daydreamer-riri** [comment]
I don't really understand this deployment, I'm glad it worked. If you have any further questions, please let me know.

**Comment by stouch** [comment]
I had to do this because your lib build the static files as : /my-page.html (instead of /my-page/index.html), and so to tell cloudfront to redirect /my-page to /my-page.html , the above code was necessary.

**Comment by Daydreamer-riri** [comment]
Oh, this configuration item may help you: https://vite-react-ssg.netlify.app/docs/Configuration#dirstyle
