### ISSUE TITLE
How to access dynamic parts of the route?

### ISSUE THREAD

**Issue by Kotyarishka** [Daydreamer-riri/vite-react-ssg#3]
Hi! I'm not sure how to access dynamic parts of the route in main component.  I was thinking something about how NextJS does it. Maybe I'm looking in wrong direction.

Thank you in advance!

**Comment by Daydreamer-riri** [comment]
Hi 🎉. Use getStaticPaths to set all paths that dynamic routing can access.

Look this: [getStaticPaths](https://github.com/Daydreamer-riri/vite-react-ssg?tab=readme-ov-file#getstaticpaths)

You can also check out this example: [with loader](https://github.com/Daydreamer-riri/vite-react-ssg/tree/main/examples/with-loader)

**Comment by Daydreamer-riri** [comment]
I will close this issue for now. If you still have any questions, please tell me.

**Comment by Daydreamer-riri** [comment]
I will close this issue for now. If you still have any questions, please tell me.
