### ISSUE TITLE
About React docs : Why this lib ?

### ISSUE THREAD

**Issue by stouch** [Daydreamer-riri/vite-react-ssg#30]
The work you've done is so amazing, we used it on our projects and we are totally satisfied.

I just create this issue to investigate why React (and more specifically the react.dev docs https://github.com/reactjs/react.dev/issues/7155) never mentioned about it ? 

Why is it not more straightforward to build and ship a SSG vite + react website ? Why did you created this lib in the first place ?

**Comment by Daydreamer-riri** [comment]
I initially created this library because I found that there was no such tool in the community that allowed me to implement SSG without using a framework. Driven by personal needs and the desire to fill this gap, I developed this library.

Thank you for your appreciation of this library!
