### ISSUE TITLE
How to deploy to GitHub pages

### ISSUE THREAD

**Issue by wonderfulMan** [Daydreamer-riri/vite-react-ssg#32]
How to deploy to GitHub pages？

After packaging and deployment, React encountered hydration errors after refreshing（react-error：418/423）

**Comment by Daydreamer-riri** [comment]
Can you provide your code repository? This can help me locate the problem.

**Comment by wonderfulMan** [comment]
repository : https://github.com/wonderfulMan/test-vite-react-ssg/tree/master

**Comment by Daydreamer-riri** [comment]
Can you try this: https://github.com/Daydreamer-riri/vite-react-ssg?tab=readme-ov-file#public-base-path

**Comment by wonderfulMan** [comment]
> I'm currently on vacation and I can't test it myself at the moment. Please try this: https://github.com/Daydreamer-riri/vite-react-ssg?tab=readme-ov-file#public-base-path



It succeeded!! Thank you for your reply. enjoy yourself
