### ISSUE TITLE
 Multiple html render like vite-plugin-html

### ISSUE THREAD

**Issue by pgmrDohan** [Daydreamer-riri/vite-react-ssg#33]
While developing with vite-react-ssg, I needed dynamic meta tags based on the page router.

Using the traditional React-helmet or Head Component didn't work with the intended result because most messaging apps read the meta tags immediately in the html response.

Therefore, I need a customizable approach based on the router, rather than having the html generated based on index.html in any case.

I think we can borrow the approach used by [vite-plugin-html](https://github.com/vbenjs/vite-plugin-html) and add related functionality to vite-react-ssg as well.

While I using both plugins together, the build process of vite-react-ssg will run after applying vite-plugin-html, overwriting the build of the existing html file.

**Comment by Daydreamer-riri** [comment]
Head which vite-react-ssg provide It inserts the meta tag into the head tag when rendering, so you don't need any other tools in the original design. I would like to know in detail what is the problem you are encountering? This will help me locate the problem.

**Comment by pgmrDohan** [comment]
> `Head` which vite-react-ssg provide It inserts the meta tag into the head tag when rendering, so you don't need any other tools in the original design. I would like to know in detail what is the problem you are encountering? This will help me locate the problem.

I developed this with [the following code](https://github.com/pgmrDohan/portfolio/blob/079b7b079a6cfee0bef419a25bd48826c13353de/src/components/Layout/index.tsx).
And this is [the result of the build](https://github.com/pgmrDohan/portfolio/blob/92722642ef34b391f6a821dec02ff51df29367ef/index.html)
As mentioned above, most messaging apps only generate embeds via the meta tag in the HTML immediately after the response, so when shared via social media, it didn't work as intended.

**Comment by pgmrDohan** [comment]
Thanks you for reply

**Comment by Daydreamer-riri** [comment]
You can also use useRouter , which allows you to get the current route information when rendering on the server, while the window can only be accessed on the client.
