### ISSUE TITLE
Refresh loader data on SSG ?

### ISSUE THREAD

**Issue by rryando** [Daydreamer-riri/vite-react-ssg#38]
Hi, first of all nice work on this! this is amazing and integrated great to our static site with less hassle!

The thing, is as the project growth more complex, 
we figured out that the `useLoader` data can't be refresh even with `revalidate` or via `action route` 
this will cause page error pointing to `static-loader-data-manifest-undefined.json`

everything works well on SSR on `vite-react-ssg dev` 

for context of our problem, we have a loader that have a generate data (on server) like  `UUID` and `feature flag`, then the data will be sent to page and sync to browser via `cookies`, 
so using loader is our priority since loader have access to `request.header`, but the thing is, 

the data generated on server is generated only once on `build` and stored on `static-loader-data-manifest`, it seems like currently there's no way we can refresh the loader to generate unique data on request;

is there any solution for this when serve as static ? or maybe is there a solution of using the SSG render alongside with data-router from react-router ?

Thank you so much!

**Comment by Daydreamer-riri** [comment]
Thank you for your appreciation. 

Regarding the issue you encountered, it's important to emphasize that SSG (Static Site Generation) does not involve a server. Everything is determined at build time. This ensures that the pages rendered at build time and the pages rendered on the client side when navigating routes are consistent. 

If you need some "dynamic" parts in your "static" page generation, I suggest you generate them on the client side or request another service from the client side. The capabilities provided by SSG do not include server-side functionalities.

**Comment by rryando** [comment]
Thank you for your reply!

I was thinking the same, 
but this idea occur to me to use `hydrateRoot` to rehydrate the static part into client side, so the `data loader` would works well after the client side rehydrate, 

ex: 
```jsx
const router = createBrowserRouter(routes);

ReactDOM.hydrateRoot(
	document.getElementById("root") as HTMLElement,
	<RouterProvider router={router} />,
);

````

the build was success, but whenever the site going to rehydrate, this error happened, 
````Unexpected Application Error!
Cannot read properties of undefined (reading 'add')
TypeError: Cannot read properties of undefined (reading 'add')
    at n.init (http://localhost:3000/assets/app-DF1Tvi3r.js:33:71332)
    at n.render (http://localhost:3000/assets/app-DF1Tvi3r.js:33:71394)
    at lu (http://localhost:3000/assets/app-DF1Tvi3r.js:33:6159)
    at lc (http://localhost:3000/assets/app-DF1Tvi3r.js:33:5956)
    at mh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:44799)
    at ph (http://localhost:3000/assets/app-DF1Tvi3r.js:33:39705)
    at Dy (http://localhost:3000/assets/app-DF1Tvi3r.js:33:39633)
    at Ds (http://localhost:3000/assets/app-DF1Tvi3r.js:33:39486)
    at gu (http://localhost:3000/assets/app-DF1Tvi3r.js:33:35853)
    at dh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:34804)
Unexpected Application Error!
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at vh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:26039)
    at Un (http://localhost:3000/assets/app-DF1Tvi3r.js:33:25745)
    at vh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:26494)
    at Un (http://localhost:3000/assets/app-DF1Tvi3r.js:33:25745)
    at vh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:26494)
    at Un (http://localhost:3000/assets/app-DF1Tvi3r.js:33:25745)
    at vh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:26819)
    at Un (http://localhost:3000/assets/app-DF1Tvi3r.js:33:25745)
    at vh (http://localhost:3000/assets/app-DF1Tvi3r.js:33:26494)
    at Zt (http://localhost:3000/assets/app-DF1Tvi3r.js:33:27348)
    ````

I know this maybe outside of `vite-react-ssg` context but, maybe you have insight about this 😄

**Comment by Daydreamer-riri** [comment]
From what I understand, I don't think loaders are the solution for your scenario. Can you describe your scene in more detail? For example, what is the reason for you choose the loader, what is your server, and what is provided.

**Comment by rryando** [comment]
okay, so I have a case of AB test that split 50:50 layout randomize for each user, 
the AB service is different service that needed UUID to be initialized, this called via api;

the most ideal way to do this is via loader since it enable us to fetch the experiment before render; 

also, on loader we can access request method sent by client, this enable the loader to acces client cookie sent by header

in this case the cookie is used to store UUID and will be used insync between client and server as follow:
- server loader: check if uuid in cookie exist, generate if not, and init AB client using uuid
- client: get uuid from loader, store uuid in browser cookie, and use it for AB client to log event


since we focusing on reducing layout shift so choosing AB layout after render is not feasible 

(we tasted the SSG performances and it hard to go back 😅)

**Comment by Daydreamer-riri** [comment]
There are a few issues with this: when the user first visits the website, no loader is executed. What the user gets directly is the HTML rendered at the build. There is no opportunity to divert here.

And the loader generated by the static page will never be executed on the server side. It doesn't have a server side, it just deploys on static resource services. So I don't know what you mean by "server loader".

> since we focusing on reducing layout shift so choosing AB layout after render is not feasible

I agree with this. I think your scenario, SSG is not a good solution, maybe you can try SSR? Like remix.

**Comment by Daydreamer-riri** [comment]
> There are a few issues with this: when the user first visits the website, no loader is executed. What the user gets directly is the HTML rendered at the build. There is no opportunity to divert here.
> 
> And the loader generated by the static page will never be executed on the server side. It doesn't have a server side, it just deploys on static resource services. So I don't know what you mean by "server loader".
> 
> > since we focusing on reducing layout shift so choosing AB layout after render is not feasible
> 
> I agree with this. I think your scenario, SSG is not a good solution, maybe you can try SSR? Like remix. Because you need to render after shredding, not on build.

**Comment by rryando** [comment]
Thank you, I agree, as our project growth complex, I think for my case SSR may be the best fit.

Thank you for amazing works and the discussion! 

I will close this issue 😊
