### ISSUE TITLE
generating not found page

### ISSUE THREAD

**Issue by joprice** [Daydreamer-riri/vite-react-ssg#46]
I can't seem to get a not found fallback page to work. I'm trying to produce the static site to be served from an nginx container. Currently, I don't get a 404 page generated. If I redirect everything to index.html, as you would with a typical spa, I get hydration errors since it's serving the wrong content. Is there an example of producing a single page alongside a 404 page I could use as a reference?

**Comment by joprice** [comment]
Just found a workaround to force the 404 page to render: Pass `getStaticPaths` with an arbitrary non-empty array such as `["not-found"]`. Then I can configure nginx with `error_page 404 /not-found/index.html`. (Not sure if it's unrelated, but on the first click on the not found page, I get `root did not complete` error in the console).

**Comment by joprice** [comment]
Found a similar Remix issue https://github.com/remix-run/remix/issues/10214

**Comment by Daydreamer-riri** [comment]
> Then I can configure nginx with error_page 404 /not-found/index.html. 
That's right. The job of vite-react-ssg is static page generation. This means that you need to explicitly handle 404 or 500 pages, just like any other page. 

On the server side, you should configure your Nginx to direct to the corresponding 404.html. On the client side, use a fallback route to display the 404 page (this is also the recommended approach by react-router: https://github.com/remix-run/react-router/blob/dev/examples/route-objects/src/App.tsx#L19).

**Comment by joprice** [comment]
That makes sense. The issue I was having was that no html file was generated for the not found page without using getStaticPaths. I assumed that was for explicitly parametrized routes, but now I see that a wildcard essentially acts as a parameter.

**Comment by Daydreamer-riri** [comment]
Is there still a problem? I will try my best to help.
