### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by jesse23** [Daydreamer-riri/vite-react-ssg#49]
Hi we have a requirement to get this work in react17, which kind of I get it work already. Do you mind a contribution with an option? Thx.

**Comment by Daydreamer-riri** [comment]
Sure, feel free to open a PR!

**Comment by jesse23** [comment]
Let me know if you are OK with the interface and modification. Thx

**Comment by Daydreamer-riri** [comment]
Released in version 0.8.3!

**Comment by jesse23** [comment]
@Daydreamer-riri  I don't know why but the import will cause error....logically it shouldn't but somehow it falls into the else block and error out (from commit `636b7acb7004d26422eca6774af2efe390ada121`)

<img width="992" alt="image" src="https://github.com/user-attachments/assets/8e533710-25bb-4950-b329-a41dcd1a89be" />

My impl (beta.1) seems OK

**Comment by jesse23** [comment]
nvm the latest 0.8.3 works great. I am not 100% sure but I guess it is related to I miss porting `CopyReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.usingClientEntryPoint` :)
