### ISSUE TITLE
Unable to recognize the base of Vite

### ISSUE THREAD

**Issue by condorheroblog** [Daydreamer-riri/vite-react-ssg#5]
```bash
# vite.config.ts
export default defineConfig({
	base: "/vite-plugin-fake-server/",
	plugins: [
		react(),
	],
});
```

```bash
# package.json

# Previously
"dev": "vite",

# Now
"dev": "vite-react-ssg dev",
```

The behavior of `vite-react-ssg dev` and `vite` is different, `vite-react-ssg dev` cannot recognize the path specified by base.

> In addition, https://github.com/antfu/vite-ssg only replaces the build command

**Comment by Daydreamer-riri** [comment]
Hi @condorheroblog , now, vite-react-ssg supports' `base`.

You can check the example here: https://github.com/Daydreamer-riri/vite-react-ssg/blob/main/examples/lazy-pages/vite.config.ts
