### ISSUE TITLE
undefined ssh hash 

### ISSUE THREAD

**Issue by joprice** [Daydreamer-riri/vite-react-ssg#51]
I'm seeing the same error as https://github.com/Daydreamer-riri/vite-react-ssg/issues/38, `static-loader-data-manifest-undefined.json`, but under circumstances I would think would work. I have some routes the work in dev, but when I attempt to route to them in the release build, I see the manifest being undefined. Taking a look at `src/node/build.ts`, I see `window.__VITE_REACT_SSG_HASH__` is used to build the manifest url, but I don't see that in my generated html files. Is there any common mistake that might lead to that?

**Comment by joprice** [comment]
I think I found the issue. Having a class on the root div `<div class="h-full flex flex-col" id="root"></div>` causes it to fail to be found.

**Comment by joprice** [comment]
I assume it's this check https://github.com/Daydreamer-riri/vite-react-ssg/blob/main/src/node/html.ts#L43-L44

**Comment by Daydreamer-riri** [comment]
Thank you for the report! It is a Bug, I need to fix it as soon as possible.

**Comment by Daydreamer-riri** [comment]
Hi @joprice, this bug has been fixed in version v0.8.3! Thank you for making this project better.
