### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'BASE_URL')

### ISSUE THREAD

**Issue by condorheroblog** [Daydreamer-riri/vite-react-ssg#6]
https://github.com/Daydreamer-riri/vite-react-ssg/blob/388d6b1095ad06996614229bf3a2f5a08419928a/src/client/index.tsx#L26

The variables above in the real code are undefined and need to be manually set by the user, similar to the following

```ts
export const createApp = ViteSSG(App, {
  base: import.meta.env.BASE_URL,
  routes,
})
```

**Comment by childrentime** [comment]
@condorheroblog  add this into your vite config 
```tsx
 ssr: {
      noExternal: ["vite-react-ssg"],
    },
```

**Comment by Daydreamer-riri** [comment]
https://github.com/vitejs/vite/issues/8952

`import.meta.env` in `node_modules` will not be processed when `noExternal` is not set.
@condorheroblog Do you think `vite-react-ssg` should expose `base` option in ViteReactSSG? Or require users to set `ssr.noExternal` option in `vite.config.ts`?

**Comment by Daydreamer-riri** [comment]
@condorheroblog Update to v0.5.2, and pass basename.

https://vite-react-ssg.netlify.app/docs/Configuration#public-base-path
