### ISSUE TITLE
[Bug] Duplicate head tag

### ISSUE THREAD

**Issue by condorheroblog** [Daydreamer-riri/vite-react-ssg#9]
```html
	<head>
		<meta charset="UTF-8" />
		<link rel="icon" href="data:," />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>vite-plugin-fake-server</title>
	</head>
```

The above is the content of my index.html file, vite-react-ssg will render it as follows

![image](https://github.com/Daydreamer-riri/vite-react-ssg/assets/47056890/f757ca03-4b59-4da3-9b46-41996f7eccbd)

---

If I use the `Head` component provided by `vite-react-ssg`, I still have this problem

```ts
import { Head as SSGHead } from "vite-react-ssg";

export function Head() {
	return (
		<header>
			<SSGHead>
				<title>vite-plugin-fake-server</title>
			</SSGHead>
		</header>
	);
}
```

![image](https://github.com/Daydreamer-riri/vite-react-ssg/assets/47056890/a5d20bcc-2355-49a9-8e58-f59ba4088b78)

**Comment by Daydreamer-riri** [comment]
Whether you encountered this bug under the `vite` command?

**Comment by condorheroblog** [comment]
> Whether you encountered this bug under the `vite` command?

No, normal under `vite` command.

**Comment by condorheroblog** [comment]
You Rock👍
